spring.application.name=mq
# application.properties
# ActiveMQ broker's default connection URL
spring.activemq.broker-url=tcp://localhost:61616

# Define the destination (queue) name for the application

jdbc.url=jdbc:sqlite:paper.db
model.name=gemini-2.5-flash
api.key=your-key

llm.queue.name=llm.queue
email.queue.name=email.queue

sender.email=luiz@barboza.me.uk
sender.pass=my-pass
recipient.email=lcbj@cesar.edu
subject=Your PDF is ready for download!
smtp.host=mail.smtp2go.com
smtp.port=2525



